# Dependency of 'francoiscabrol/ranger.vim'.
[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'glacambre/firenvim'
hook_post_update = '''
    call firenvim#install(0)
'''
hook_source = '''
    function! OnUIEnter(event) abort
        if 'Firenvim' ==# get(get(nvim_get_chan_info(a:event.chan), 'client', {}), 'name', '')
            set laststatus=0
        endif
    endfunction
    autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
    au BufEnter github.com_*.txt set filetype=markdown
    au BufEnter eprosima.easyredmine.com_*.txt set filetype=markdown
    au BufEnter mail.google.com_*.txt set filetype=markdown
    au BufEnter chat.google.com_*.txt set filetype=markdown
    nnoremap <Esc><Esc> :call firenvim#focus_page()<CR>
'''

# Use ranger inside Vim
[[plugins]]
repo = 'francoiscabrol/ranger.vim'
depends = 'bclose.vim'
merged = 0
hook_source = '''
    let g:NERDTreeHijackNetrw = 0 " add this line if you use NERDTree
    let g:ranger_replace_netrw = 1 " open ranger when vim open a directory

    let g:ranger_map_keys = 0
    map <leader>r :set nonumber<CR> :Ranger<CR> :set number<CR>
'''
