########################################################################################################################
# Plugins used to decorate Vim.                                                                                        #
########################################################################################################################

[[plugins]]
repo = 'ryanoasis/vim-devicons'
