[[plugins]]
repo = 'jeaye/color_coded'
build = 'cmake -DDOWNLOAD_CLANG=FALSE . && make && make install'
on_ft = ['c', 'cpp', 'objc', 'objcpp']

# Plugin para expandir % a HTML, LaTex, ...
[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'dnguyen85/vim-pyclewn'

# Plugins necessary for deocomplete.vim
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
