########################################################################################################################
# Plugins for perform searching.                                                                                       #
########################################################################################################################

[[plugins]]
# Plugin used to find files.
repo = 'junegunn/fzf.vim'
merged = 0
hook_source = 'source ~/.vim/rc/plugins/fzf.rc.vim'
hook_add = '''
    nnoremap <silent> <Leader>t
        \ :call FzfFilePreview()<CR>
'''

[[plugins]]
# Plugin used to list tags in a sidebar.
repo = 'majutsushi/tagbar'
hook_add = '''
    nmap <F10> :TagbarToggle<CR>
    let g:tagbar_position = "left"
'''

# TODO Fix when LUA support is in neovim (hightlight can be don by other plugin that use LUA)
[[plugins]]
# Support for easytags
repo = 'xolox/vim-easytags'
depends = 'vim-misc'
hook_source = '''
    let g:easytags_always_enabled = 0
    let g:easytags_events = ['BufWritePost']
    let g:easytags_file = 'tags'
    let g:easytags_auto_highlight = 0
    let g:easytags_updatetime_min = 5000
    let g:easytags_async = 1
    " let g:easytags_opts = ['--c-kinds=+p', '--c++-kinds=+p', '--fields=+liaS', '--extra=+q', '--exclude=build']
    let g:easytags_suppress_ctags_warning = 1
'''

[[plugins]]
# Auxiliary plugin adding support for markdown files in tagbar.
repo = 'jszakmeister/markdown2ctags'
build = 'pip install --user markdown2ctags'
hook_source = '''
    let g:tagbar_type_vimwiki = {
        \ 'ctagstype': 'markdown',
        \ 'ctagsbin' : 'markdown2ctags',
        \ 'ctagsargs' : '-f - --sort=yes --sro=»',
        \ 'kinds' : [
            \ 's:sections',
            \ 'i:images'
        \ ],
        \ 'sro' : '»',
        \ 'kind2scope' : {
            \ 's' : 'section',
        \ },
        \ 'sort': 0,
    \ }
'''
